/**
 * 04_system_design.js
 * ─────────────────────────────────────────
 * CHAPTER 4 — System Design
 * ─────────────────────────────────────────
 */

const { h1, h2, h3, h4, jpp, jp, bul, sp, sp2, pb, tbl, codeBlock } = require('./helpers');

const content = [

    h1('CHAPTER 4: SYSTEM DESIGN'),

    jpp('This chapter presents the complete system design of TASKTIME — from the high-level architectural layers down to the field-level database entity definitions, the dual-path AI pipeline architecture, the billing system, and the productivity scoring algorithm. Every design decision documented here is grounded in the requirements established in Chapter 3 and directly implemented in the code described in Chapter 5.'),
    sp(),

    // ─── 4.1 Basic Modules ───────────────────────────────
    h2('4.1 Basic Modules'),
    jpp('TASKTIME is decomposed into eight major functional modules, each encapsulating a distinct domain of responsibility:'),
    sp(),
    tbl(
        ['Module', 'Responsibility', 'Key Files'],
        [
            ['1. User Authentication Module', 'Registration, email OTP verification, JWT token management (issue, refresh, revoke), password reset, session management across devices', 'auth.controller.js, auth.service.js, jwt.util.js, otp.util.js'],
            ['2. Task Management Module', 'Task CRUD, category management, priority filtering, soft deletion, monthly usage limits, task completion tracking per day', 'task.controller.js, task.service.js, category.service.js'],
            ['3. Schedule Management Module', 'Schedule creation with conflict detection, four recurrence types, schedule completion tracking, missed schedule detection via cron', 'schedule.controller.js, schedule.service.js, appliesOnDate() in date.utils.js'],
            ['4. AI Assistant Module', 'Multi-model AI routing, LangGraph pipeline orchestration, Sarvam-M JSON router, streaming SSE responses, AI message persistence, credit consumption', 'aiOrchestrator.service.js, main.graph.js, sarvam/graph.js, all tools'],
            ['5. Voice Processing Module', 'Speech-to-text (Sarvam Saaras v3 + OpenAI Whisper), text-to-speech (Sarvam Bulbul v3 + OpenAI TTS-1), S3 audio storage, Pro+ plan enforcement', 'stt.service.js, tts.service.js, voice.controller.js'],
            ['6. Behavioral Analytics Module', 'Daily mood/sleep/exercise logging, behavior score calculation, productivity composite score, streak tracking', 'behavior.controller.js, behavior.service.js, score.utils.js'],
            ['7. Dashboard Module', 'Today\'s workload aggregation, productivity score display, streak count, upcoming schedule timeline, quick stats', 'dashboard.controller.js, dashboard.service.js'],
            ['8. Billing Module', 'Razorpay subscription creation, credit top-up orders, HMAC-verified webhook handling, atomic credit grant/deduction, subscription status management', 'billing.controller.js, billing.service.js, razorpay.webhook.js, aiToken.service.js'],
        ],
        [2200, 3500, 3660],
    ),
    sp(),

    // ─── 4.2 System Architecture ─────────────────────────
    h2('4.2 System Architecture'),
    jpp('TASKTIME follows a client-server architecture with full separation between the frontend Next.js application and the backend Express.js API. The two communicate exclusively via JSON over HTTPS. The backend is completely stateless — all session state is maintained through JWT tokens and the PostgreSQL database, enabling horizontal scaling.'),
    sp(),
    tbl(
        ['Layer', 'Technology', 'Hosting', 'Responsibility'],
        [
            ['Client (Presentation)', 'Next.js 16 + React 19 + Tailwind CSS 4', 'Vercel Global CDN', 'SSR public pages, SPA dashboard, AI chat UI, calendar, billing'],
            ['API Gateway', 'Express.js 5 + CORS + Helmet + Morgan', 'Node.js Server', 'HTTP routing, request parsing, security headers, CORS enforcement'],
            ['Authentication Layer', 'JWT + bcrypt + cookie-parser', 'Node.js Middleware', 'Token validation, session lookup, role enforcement on every request'],
            ['Application Layer', '15+ Controller files', 'Node.js', 'Business logic orchestration, input validation, error handling'],
            ['Service Layer', '12+ Service files', 'Node.js', 'Core business rules — conflict detection, score calculation, credit billing'],
            ['AI Orchestration', 'LangGraph + LangChain + Custom Sarvam Router', 'Node.js', 'Multi-model routing, tool execution, streaming, context building'],
            ['Data Access Layer', 'Prisma ORM 6', 'Node.js', 'Type-safe parameterized queries, schema migrations, transaction management'],
            ['Database', 'PostgreSQL 16', 'Supabase (AWS ap-south-1)', '18 models, 15 enums, UUID PKs, cascade deletes, B-Tree indexes'],
            ['Background Jobs', 'node-cron', 'Node.js', '3 scheduled jobs: missed schedules (00:05 UTC), credit expiry, yearly drip'],
            ['External AI APIs', 'Gemini, OpenAI, Sarvam AI', 'Third-party Cloud', 'LLM inference, STT transcription, TTS synthesis'],
            ['Payment Gateway', 'Razorpay', 'Third-party', 'Subscription lifecycle, payment processing, HMAC-signed webhooks'],
        ],
        [2000, 2200, 1800, 3360],
    ),
    sp(),

    h3('4.2.1 Backend Folder Structure'),
    ...codeBlock([
        'backend/src/',
        '├── ai/                           ← Complete AI system',
        '│   ├── controllers/              ← HTTP handlers for AI endpoints',
        '│   ├── graph/                    ← LangGraph nodes, edges, state',
        '│   │   ├── main.graph.js         ← Graph compiler + model factory + cache',
        '│   │   ├── contentUtils.js       ← normalizeContent() Gemini/OpenAI formats',
        '│   │   ├── nodes/',
        '│   │   │   ├── planner.node.js   ← Intent classification + planning hints',
        '│   │   │   ├── intent.node.js    ← Main agent (LLM invocation + tool calls)',
        '│   │   │   ├── tool.node.js      ← Tool execution via LangGraph ToolNode',
        '│   │   │   ├── reflection.node.js← Error detection + retry guidance injection',
        '│   │   │   └── finalize.node.js  ← Response format normalization',
        '│   │   └── edges.js              ← shouldContinue() conditional routing',
        '│   ├── memory/',
        '│   │   └── behavior.memory.js    ← Last 3 behavior logs for AI context',
        '│   ├── prompts/',
        '│   │   └── system.prompt.js      ← TASKTIME identity, scheduling rules, limits',
        '│   ├── sarvam/                   ← Custom Sarvam-M routing system',
        '│   │   ├── executor.js           ← Maps action strings to service calls',
        '│   │   ├── graph.js              ← 4-node Sarvam graph compiler',
        '│   │   ├── nodes.js              ← extractor, validator, executor, response',
        '│   │   └── prompts.js            ← Intent parser prompt (14 actions + examples)',
        '│   ├── services/',
        '│   │   ├── aiOrchestrator.service.js ← Entry point: model resolution, billing',
        '│   │   ├── aiContext.service.js      ← buildSystemContext() parallel fetch',
        '│   │   └── aiToken.service.js        ← calcChatCost(), deductCredits()',
        '│   ├── tools/                    ← LangChain DynamicStructuredTool definitions',
        '│   │   ├── task.tool.js          ← create_task, bulk, update, delete, list',
        '│   │   ├── schedule.tool.js      ← create_schedule, bulk, update, delete',
        '│   │   ├── behavior.tool.js      ← log_behavior',
        '│   │   └── dashboard.tool.js     ← get_dashboard_summary',
        '│   └── voice/',
        '│       ├── stt.service.js        ← Sarvam Saaras v3 + OpenAI Whisper STT',
        '│       └── tts.service.js        ← Sarvam Bulbul v3 + OpenAI TTS-1',
        '├── config/',
        '│   ├── db.js                     ← Prisma client singleton (prevent re-init)',
        '│   └── plans.config.js           ← AI_COSTS, PLANS, TOP_UP_PLANS, MODEL_INFO',
        '├── controllers/                  ← Auth, task, schedule, billing, dashboard...',
        '├── cron/                         ← missedSchedule.cron.js, creditExpiry.cron.js',
        '├── middlewares/                  ← authenticate.js, usageLimit.js, planGuard.js',
        '├── routes/                       ← Express Router definitions (9 modules)',
        '├── services/                     ← auth, task, schedule, billing, dashboard...',
        '├── utils/                        ← jwt.js, otp.js, date.utils.js, score.utils.js',
        '└── webhooks/                     ← razorpay.webhook.js (HMAC verify + process)',
    ]),
    sp(),

    // ─── 4.3 Database Design ─────────────────────────────
    h2('4.3 Database Design'),

    h3('4.3.1 Entity Relationship Overview'),
    jpp('The TASKTIME database contains 18 entities (models) with User as the central node. All other entities have a direct foreign key relationship to User with onDelete: Cascade, ensuring clean data removal when a user account is deleted. The ERD follows a star schema where task/schedule/behavior/billing entities are satellite tables around the central User entity.'),
    sp(),
    tbl(
        ['Entity', 'Records Per User (Approx)', 'Purpose'],
        [
            ['User', '1', 'Central identity: credentials, plan, AI preferences, credit balances'],
            ['Session', '1–5', 'JWT refresh token hashes; one record per active login device'],
            ['Otp', '1–3 (short-lived)', 'Temporary OTP hashes for email verification, password reset'],
            ['Task', 'Up to 1000/month', 'Core work unit: title, description, priority, dueDate, category'],
            ['Category', '5–20', 'User-defined task groupings with colour and icon'],
            ['Schedule', 'Up to 500/month', 'Time block linked to a task: date, start/end time, recurrence pattern'],
            ['ScheduleCompletion', 'Per schedule per day', 'Immutable completion record for each schedule occurrence'],
            ['TaskDailyCompletion', 'Per task per day', 'Daily task completion for streak calculation'],
            ['MissedSchedule', 'Per missed occurrence', 'Written nightly by cron for uncompleted schedule occurrences'],
            ['BehaviorLog', '1 per day', 'Mood, sleep hours, exercise boolean — upserted daily'],
            ['Subscription', '0–1', 'Active plan details: cycle, credits, billing dates, Razorpay subscription ID'],
            ['UsageStat', '1 per month', 'Running counts of tasks/schedules created this month for limit enforcement'],
            ['Payment', '1 per transaction', 'Every Razorpay transaction record (subscription charge, top-up)'],
            ['AiCreditLedger', '1 per AI request', 'Immutable audit trail of all credit grants and deductions'],
            ['AiConversation', '1–50', 'Chat session container with title, type, total credits used'],
            ['AiMessage', 'Many per conversation', 'Individual chat messages: role (USER/ASSISTANT/SYSTEM), content, model'],
            ['AiUsage', '1 per AI request', 'Detailed AI usage record: model, type (CHAT/VOICE), credits consumed'],
            ['AiTopUp', '1 per top-up purchase', 'Links payment record to credit top-up grant'],
        ],
        [2500, 2200, 4660],
    ),
    sp(),

    h3('4.3.2 User Entity — Complete Field Reference'),
    tbl(
        ['Field', 'Type', 'Default', 'Description'],
        [
            ['id', 'String (UUID)', 'uuid()', 'Primary key. UUID prevents enumeration attacks.'],
            ['name', 'String', 'Required', 'Display name. Shown in UI and injected into AI context.'],
            ['email', 'String (Unique)', 'Required', 'Login email. B-Tree indexed. Unique constraint enforced.'],
            ['password', 'String', 'Required', 'bcrypt hash, cost factor 10. Plain text never stored.'],
            ['isEmailVerified', 'Boolean', 'false', 'Set true after OTP verification. Unverified users cannot login.'],
            ['timezone', 'String?', 'null', 'IANA timezone (e.g. "Asia/Kolkata"). Used in buildSystemContext().'],
            ['role', 'UserRole', 'USER', 'USER or ADMIN. ADMIN bypasses all usage limits.'],
            ['plan', 'PlanType', 'FREE', 'Current subscription plan. Updated by Razorpay webhook handler.'],
            ['status', 'AccountStatus', 'ACTIVE', 'ACTIVE, SUSPENDED, or DELETED lifecycle state.'],
            ['subscriptionCredits', 'Int', '0', 'Monthly plan credits. Expire on billing date. Consumed first.'],
            ['topupCredits', 'Int', '0', 'One-time purchase credits. Never expire. Consumed after subscription credits.'],
            ['subscriptionCreditsExpiresAt', 'DateTime?', 'null', 'When subscription credits expire. Null for free tier.'],
            ['aiChatModel', 'String', '"sarvam-m"', 'User\'s preferred text chat model. FREE users locked to sarvam-m.'],
            ['aiVoiceModel', 'String', '"sarvam-m"', 'Preferred AI model for voice thinking step.'],
            ['aiTtsModel', 'String', '"bulbul:v3"', 'Text-to-speech model preference.'],
            ['aiSttModel', 'String', '"saaras:v3"', 'Speech-to-text model preference.'],
            ['aiSarvamLang', 'String', '"unknown"', 'Sarvam TTS language override. "unknown" = auto-detect.'],
            ['aiSarvamSpeaker', 'String', '"shubh"', 'Sarvam Bulbul voice speaker name (14 available voices).'],
            ['tokenVersion', 'Int', '1', 'Incremented on password change. Invalidates all existing sessions.'],
        ],
        [2400, 1800, 1500, 3660],
    ),
    sp(),

    h3('4.3.3 Task Entity'),
    tbl(
        ['Field', 'Type', 'Description'],
        [
            ['id', 'String (UUID)', 'Primary key.'],
            ['title', 'String', 'Task title — required. AI rules mandate null dueDate unless user specifies.'],
            ['description', 'String?', 'Optional detailed description.'],
            ['priority', 'TaskPriority', 'LOW / MEDIUM / HIGH. Default MEDIUM.'],
            ['dueDate', 'DateTime?', 'NULL by default. Set only when user explicitly mentions a deadline. Tasks with dueDate CANNOT be scheduled.'],
            ['order', 'Int?', 'Manual sort order for drag-and-drop reordering.'],
            ['categoryId', 'String?', 'FK to Category. OnDelete: SetNull (task remains when category deleted).'],
            ['isArchived', 'Boolean', 'Soft-delete flag. Default false. Archived tasks excluded from active lists.'],
            ['deletedAt', 'DateTime?', 'Timestamp of soft deletion. NULL = active task.'],
            ['taskDate', 'DateTime (Date)', 'Date task was created — used for day-level analytics.'],
        ],
        [2200, 1800, 5360],
    ),
    sp(),

    h3('4.3.4 Schedule Entity — Design Decisions'),
    tbl(
        ['Field', 'Type', 'Design Rationale'],
        [
            ['scheduleDate', 'DateTime (@db.Date)', 'Anchor date for the schedule. For recurring schedules, this is the FIRST occurrence. Date-only storage prevents timezone conversion issues.'],
            ['startTime', 'DateTime (@db.Time)', 'Time-only field. Stored as 1970-01-01T{HH:mm:ss}Z for consistent cross-timezone comparison in conflict detection.'],
            ['endTime', 'DateTime (@db.Time)', 'Must be after startTime. Validated at service layer before database write.'],
            ['recurrence', 'RecurrenceType', 'NONE (default), DAILY, WEEKLY, MONTHLY. AI prompt rules: "Only set non-NONE if user explicitly says repeat/daily/every/weekly/monthly".'],
            ['repeatOnDays', 'Int[]', 'PostgreSQL native array. Only meaningful for WEEKLY recurrence. [1,3] = every Monday + Wednesday. 0=Sun, 1=Mon … 6=Sat.'],
            ['repeatUntil', 'DateTime? (@db.Date)', 'Optional end date for recurrence. NULL = repeat indefinitely. Used by appliesOnDate() for expiry check.'],
        ],
        [2000, 2000, 5360],
    ),
    sp(),

    h3('4.3.5 Complete Enum Reference'),
    tbl(
        ['Enum', 'Values', 'Used In'],
        [
            ['TaskPriority', 'LOW, MEDIUM, HIGH', 'Task.priority'],
            ['RecurrenceType', 'NONE, DAILY, WEEKLY, MONTHLY', 'Schedule.recurrence'],
            ['Mood', 'HAPPY, NEUTRAL, SAD', 'BehaviorLog.mood'],
            ['OtpPurpose', 'EMAIL_VERIFICATION, PASSWORD_RESET, SECURITY_ACTION', 'Otp.purpose'],
            ['UserRole', 'USER, ADMIN', 'User.role'],
            ['AccountStatus', 'ACTIVE, SUSPENDED, DELETED', 'User.status'],
            ['PlanType', 'FREE, PRO, PRO_PLUS', 'User.plan, Subscription.plan'],
            ['BillingCycle', 'MONTHLY, YEARLY', 'Subscription.billingCycle'],
            ['AiUsageType', 'CHAT, VOICE', 'AiUsage.type'],
            ['CreditSource', 'PLAN_CYCLE, TOP_UP, REFUND, AI_USAGE', 'AiCreditLedger.source'],
            ['AiMessageRole', 'USER, ASSISTANT, SYSTEM', 'AiMessage.role'],
            ['AiConversationType', 'GENERAL, DAILY_PLANNING, REFLECTION, VOICE', 'AiConversation.type'],
            ['PaymentPurpose', 'SUBSCRIPTION, TOP_UP, REFUND', 'Payment.purpose'],
            ['PaymentStatus', 'CREATED, PAID, FAILED, REFUNDED', 'Payment.status'],
            ['RazorpayEntity', 'PAYMENT, SUBSCRIPTION, INVOICE', 'Payment.entity'],
        ],
        [2000, 3500, 3860],
    ),
    sp(),

    // ─── 4.4 AI Pipeline Design ──────────────────────────
    h2('4.4 AI Pipeline Architecture'),

    h3('4.4.1 Dual-Path Model Routing'),
    jpp('The most critical architectural decision in TASKTIME\'s AI system is the dual-path routing based on each model\'s tool-calling capability. Tool calling (also called function calling) is the ability of an AI model to identify when it should invoke an external function and to output the function name and parameters in a structured JSON format. This capability is essential for TASKTIME\'s autonomous task management because the AI must not just suggest what to do but actually create, update, or delete database records on behalf of the user.'),
    sp(),
    tbl(
        ['Model', 'Tool Calling', 'Processing Path', 'Plan'],
        [
            ['gemini-1.5-flash', 'Yes — native', '5-node LangGraph agentic pipeline', 'PRO, PRO_PLUS'],
            ['gpt-4o-mini', 'Yes — native (OpenAI standard)', '5-node LangGraph agentic pipeline', 'PRO, PRO_PLUS'],
            ['sarvam-30b', 'Yes — OpenAI-compatible API', '5-node LangGraph agentic pipeline', 'PRO, PRO_PLUS'],
            ['sarvam-m', 'No — chat only', 'Custom 4-node JSON routing graph', 'FREE, PRO, PRO_PLUS'],
        ],
        [2200, 1800, 3200, 2160],
    ),
    sp(),

    h3('4.4.2 Five-Node LangGraph Pipeline'),
    tbl(
        ['Node', 'Name', 'Input', 'Processing', 'Output'],
        [
            ['1', 'Planner Node', 'Last user message from state.messages', 'Keyword matching and optional LLM classification. Identifies intent category: CALENDAR_QUERY / PLANNING / TASK_MANAGEMENT / RESEARCH / REFLECTION.', 'Optional SystemMessage [PLANNER GUIDE] injected to prime the next LLM call.'],
            ['2', 'Agent Node (Intent)', 'Full messages array + AI model config', 'Calls buildSystemContext() for rich context. Invokes LLM with all bound tools. Model decides which tools to call or returns final text.', 'AIMessage with tool_calls[] OR final text response (if no tools needed).'],
            ['3', 'Tool Node', 'AIMessage with tool_calls[]', 'LangGraph\'s ToolNode executes all requested tools in parallel. Each tool calls actual backend service (taskService, scheduleService, behaviorService).', 'ToolMessage objects with stringified JSON results from each service call.'],
            ['4', 'Reflection Node', 'ToolMessage results from step 3', 'Normalizes tool content to string. Scans for error markers: "Error:", "success: false", "failed". If detected: injects correction guidance SystemMessage for retry.', 'Conditional guidance SystemMessage, or empty state update if no errors.'],
            ['5', 'Finalize Node', 'Final state after all tool execution', 'Normalizes Gemini\'s Array<{type, text}> content format to plain string. Ensures consistent message types for downstream state management.', 'Updated state with normalized string content ready for streaming.'],
        ],
        [600, 1600, 1800, 2800, 2560],
    ),
    sp(),

    h3('4.4.3 shouldContinue() — Edge Logic'),
    ...codeBlock([
        '// edges.js — determines which node executes after the Agent Node',
        'export const shouldContinue = (state) => {',
        '  const lastMessage = state.messages.at(-1);',
        '',
        '  // If the last message is an AIMessage with tool_calls → go to Tool Node',
        '  if (lastMessage?.tool_calls?.length > 0) {',
        '    return "tools";',
        '  }',
        '',
        '  // Otherwise the model has generated a final text response → stop',
        '  return "__end__";',
        '};',
    ]),
    sp(),

    h3('4.4.4 Four-Node Sarvam-M Manual Routing Graph'),
    tbl(
        ['Node', 'Name', 'Processing', 'Output'],
        [
            ['1', 'Intent Extractor', 'Sends full conversation history + intentPrompt to Sarvam-M. Temperature = 0 for deterministic output. Prompt defines 16 valid actions with exact parameter names and 15 example conversations.', '{"thought": "User wants to schedule gym", "action": "create_task_and_schedule", "data": {"title": "Gym", "scheduleDate": "2026-03-07", "startTime": "07:00:00", "recurrence": "NONE"}}'],
            ['2', 'Validate Intent', 'Strips markdown fences (```json). Extracts JSON via regex. Parses JSON. Validates action name against list of 16 valid action strings. Returns {action: "unknown"} on any parsing or validation failure — never throws.', '{action: "create_task_and_schedule", data: {...}}'],
            ['3', 'Action Executor', 'Maps action string to service function. For create_task_and_schedule: (1) taskService.createTask() → get taskId, (2) scheduleService.createSchedule({taskId, ...data}). For unknown: skips execution.', '{success: true, task: {...}, schedule: {...}} or error details'],
            ['4', 'Response Generator', 'If action = "unknown": invokes Sarvam-M in plain chat mode (no tools). If action executed: formats natural language confirmation using execution result data. Streams response to caller.', 'AI response text: "I\'ve scheduled your gym workout for tomorrow at 7 AM. Good luck!"'],
        ],
        [600, 1800, 3500, 3460],
    ),
    sp(),

    // ─── 4.5 Scoring Algorithm ───────────────────────────
    h2('4.5 Productivity Scoring Algorithm'),

    h3('4.5.1 Behavior Score Calculation'),
    tbl(
        ['Input', 'Condition', 'Points Awarded', 'Max Points', 'Rationale'],
        [
            ['sleepHours', '>= 7 hours', '+40', '40', '7+ hours is the WHO-recommended minimum for cognitive function.'],
            ['sleepHours', '>= 5 and < 7', '+20', '40', 'Acceptable sleep — partial penalty for sub-optimal rest.'],
            ['sleepHours', '< 5 or null', '+0', '40', 'Sleep deprivation clinically impairs productivity.'],
            ['exercise', 'true', '+30', '30', 'Physical activity directly correlates with focus and energy.'],
            ['exercise', 'false', '+0', '30', 'No exercise — no bonus but no penalty.'],
            ['mood', 'HAPPY', '+30', '30', 'Positive mood state associated with higher output quality.'],
            ['mood', 'NEUTRAL', '+15', '30', 'Baseline state — average productivity expected.'],
            ['mood', 'SAD', '+0', '30', 'Low mood — supportive response, not penalised.'],
        ],
        [1400, 1800, 1400, 1200, 3760],
    ),
    sp(),

    h3('4.5.2 Composite Productivity Formula'),
    ...codeBlock([
        '// Step 1: Task Execution Score (0-100 base)',
        'let executionScore = (total > 0) ? (completed / total) * 100 : 0;',
        '',
        '// Step 2: Missed task penalty (-5 per missed, max total penalty = -20)',
        'executionScore -= Math.min(missed * 5, 20);',
        'executionScore = clamp(executionScore, 0, 100);',
        '',
        '// Step 3: Composite = 70% execution weight + 30% behavior weight',
        'const finalScore = (executionScore * 0.70) + (behaviorScore * 0.30);',
        '',
        'return clamp(Math.round(finalScore), 0, 100);',
    ]),
    sp(),
    jpp('The 70/30 weighting was chosen after analysis of academic research on productivity drivers. Task execution (70%) is the most objective and directly measurable productivity indicator. Behavioral health (30%) is a strong predictor of future performance — a person with consistently high behavioral scores builds the habits that sustain execution quality over time. The composite formula rewards whole-person productivity, not just task throughput.'),
    sp(),

    // ─── 4.6 Billing System Design ───────────────────────
    h2('4.6 Billing System Design'),

    h3('4.6.1 Subscription Plans'),
    tbl(
        ['Plan', 'Monthly Credits', 'Yearly Credits', 'Monthly Price', 'Yearly Price', 'Task Limit', 'Schedule Limit'],
        [
            ['FREE', '1000 (trial only)', '—', '₹0', '₹0', '200/month', '50/month'],
            ['PRO', '300/month', '3,600/year', '₹29', '₹299', '300/month', '100/month'],
            ['PRO_PLUS', '900/month', '10,800/year', '₹79', '₹799', '1000/month', '500/month'],
        ],
        [1200, 1500, 1500, 1500, 1500, 1400, 1260],
    ),
    sp(),

    h3('4.6.2 AI Credit Costs'),
    tbl(
        ['Model', 'Type', 'Base Cost', 'Per 1,000 Tokens', 'Max Per Call'],
        [
            ['gemini-1.5-flash', 'CHAT', '1 credit', '1 credit', '80 credits'],
            ['gpt-4o-mini', 'CHAT', '1 credit', '2 credits', '200 credits'],
            ['sarvam-m', 'CHAT', '1 credit', '2 credits', '200 credits'],
            ['sarvam-30b', 'CHAT', '1 credit', '2 credits', '200 credits'],
            ['saaras:v3 (Sarvam STT)', 'VOICE', '—', '—', '8 credits/min'],
            ['bulbul:v3 (Sarvam TTS)', 'VOICE', '—', '—', '15 credits/min'],
            ['whisper-1 (OpenAI STT)', 'VOICE', '—', '—', '10 credits/min'],
            ['tts-1 (OpenAI TTS)', 'VOICE', '—', '—', '20 credits/min'],
            ['Tavily Web Search', 'TOOL', '10 credits', '—', '—'],
        ],
        [2000, 1200, 1400, 1800, 2960],
    ),
    sp(),

    h3('4.6.3 Atomic Credit Deduction Design'),
    jpp('Credit deduction uses Prisma\'s $transaction() to guarantee atomicity. The priority rule — consume subscription credits before top-up credits — is enforced within the transaction. This prevents any scenario where a failed intermediate step leaves the user\'s balance in an inconsistent state:'),
    ...codeBlock([
        '// Three operations in ONE atomic transaction',
        'await prisma.$transaction(async (tx) => {',
        '  // 1. Fetch current balances',
        '  const user = await tx.user.findUnique({ where: { id: userId },',
        '    select: { subscriptionCredits: true, topupCredits: true }',
        '  });',
        '',
        '  // 2. Priority split: subscription first, topup for remainder',
        '  const fromSub   = Math.min(user.subscriptionCredits, amount);',
        '  const fromTopup = amount - fromSub;',
        '',
        '  // 3. Decrement both balances',
        '  await tx.user.update({ where: { id: userId }, data: {',
        '    subscriptionCredits: { decrement: fromSub },',
        '    topupCredits:        { decrement: fromTopup }',
        '  }});',
        '',
        '  // 4. Write immutable audit ledger record',
        '  await tx.aiCreditLedger.create({ data: {',
        '    userId, credits: -amount, source: "AI_USAGE",',
        '    reason: `sub:${fromSub} + topup:${fromTopup}`,',
        '    conversationId',
        '  }});',
        '});',
    ]),

    pb(),
];

module.exports = { content };