/**
 * 05_implementation.js
 * ─────────────────────────────────────────
 * CHAPTER 5 — Implementation
 * ─────────────────────────────────────────
 */

const { h1, h2, h3, h4, jpp, jp, bul, num, sp, sp2, pb, tbl, codeBlock } = require('./helpers');

const content = [

    h1('CHAPTER 5: IMPLEMENTATION'),

    jpp('This chapter describes the implementation of the TASKTIME system, including the development of its core modules such as user authentication, task management, AI assistant integration, database interactions, and API services. It explains the technologies used, coding practices followed, and how different components were integrated to build the complete application.'),
    sp(),

    // ─── 5.1 Implementation Approaches ───────────────────
    h2('5.1 Implementation Approaches'),

    h3('5.1.1 Development Methodology'),
    jpp('TASKTIME was developed using Agile Scrum with two-week sprint cycles. Each sprint had a clear goal, a prioritised backlog drawn from the requirements list in Chapter 3, and a Definition of Done requiring the feature to be: coded, locally tested, peer-reviewed, merged to main, and auto-deployed to Vercel staging. This approach meant the application was in a deployable state at the end of every sprint.'),
    sp(),

    h3('5.1.2 Code Architecture Principles'),
    tbl(
        ['Principle', 'Implementation'],
        [
            ['Separation of Concerns', 'Routes only define paths. Controllers handle HTTP concerns (parse body, send response). Services contain all business logic. Neither controllers nor routes touch the database directly.'],
            ['Single Responsibility', 'Each service file manages one domain: taskService.js only manages tasks. aiToken.service.js only manages credit billing. No god objects.'],
            ['DRY (Don\'t Repeat Yourself)', 'appliesOnDate() used in both conflict detection (schedule creation) and cron job. score.utils.js exports two pure functions reused across dashboard and behavior modules.'],
            ['Fail-Fast Validation', 'Input validation at controller level using Zod schemas before any service call. AI tool parameters validated with Zod DynamicStructuredTool schemas before execution.'],
            ['Immutable Audit Trails', 'AiCreditLedger records are never updated or deleted. PaymentStatus follows a one-way lifecycle: CREATED → PAID or FAILED. Financial data is append-only.'],
        ],
        [2200, 7160],
    ),
    sp(),

    // ─── 5.2 Key Implementations ─────────────────────────
    h2('5.2 Coding Details — Key Implementations'),

    h3('5.2.1 Express App Configuration and CORS'),
    jpp('The Express application (app.js) configures CORS using a dynamic origin function rather than a wildcard, accepting requests only from known frontend origins. The credentials: true flag is mandatory for HttpOnly refresh token cookies to be included in cross-origin requests:'),
    sp(),
    ...codeBlock([
        'app.use(cors({',
        '  origin: (origin, callback) => {',
        '    if (!origin) return callback(null, true);  // server-to-server / curl',
        '    const allowed =',
        '      origin.includes("localhost") ||',
        '      origin.includes("vercel.app") ||',
        '      origin.includes("tasktime.in");',
        '    if (allowed) return callback(null, true);',
        '    callback(new Error("CORS: Origin not permitted"));',
        '  },',
        '  credentials: true   // required for HttpOnly refresh cookie',
        '}));',
        'app.use(helmet());        // 14 security headers',
        'app.use(morgan("dev"));   // HTTP request logging',
        'app.use(cookieParser());  // parse HttpOnly cookies',
        'app.use(express.json());  // JSON body parsing',
    ]),
    sp(),

    h3('5.2.2 JWT Dual-Token Authentication'),
    jpp('Access tokens (15-minute lifetime) are sent in the Authorization header. Refresh tokens (7-day or 30-day lifetime) are stored as HttpOnly cookies. The refresh token hash is stored in the Session table — enabling server-side revocation without rotating a global secret. The tokenVersion field on User is incremented on password change to mass-invalidate all existing refresh tokens:'),
    sp(),
    ...codeBlock([
        '// jwt.util.js',
        'export const signAccessToken = (userId, role, jti) =>',
        '  jwt.sign({ userId, role, jti }, ACCESS_SECRET, { expiresIn: "15m" });',
        '',
        'export const signRefreshToken = (userId, tokenVersion, rememberMe = false) =>',
        '  jwt.sign({ userId, tokenVersion }, REFRESH_SECRET,',
        '           { expiresIn: rememberMe ? "30d" : "7d" });',
        '',
        '// auth.service.js — store hashed token for server-side revocation',
        'const tokenHash = crypto.createHash("sha256")',
        '  .update(refreshToken).digest("hex");',
        '',
        'await prisma.session.create({',
        '  data: {',
        '    accessTokenJti: jti,',
        '    refreshTokenHash: tokenHash,',
        '    userId,',
        '    expiresAt: new Date(Date.now() + expiryMs),',
        '    isPersistent: rememberMe',
        '  }',
        '});',
    ]),
    sp(),

    h3('5.2.3 OTP Generation and Hashing'),
    jpp('OTP codes are generated using Node.js\'s built-in crypto.randomInt() for cryptographically secure random numbers. The plaintext OTP is emailed to the user but only the SHA-256 hash is stored in the database — a breach of the database cannot reveal OTP codes:'),
    sp(),
    ...codeBlock([
        '// otp.util.js',
        'export const generateOtp = () => {',
        '  // Cryptographically secure 6-digit code (100000–999999)',
        '  const raw = crypto.randomInt(100000, 999999).toString();',
        '  const hash = crypto.createHash("sha256").update(raw).digest("hex");',
        '  return { raw, hash };  // raw → email, hash → database',
        '};',
        '',
        '// Verification: hash the submitted code and compare',
        'export const verifyOtp = (submitted, storedHash) => {',
        '  const submittedHash = crypto.createHash("sha256")',
        '    .update(submitted).digest("hex");',
        '  return submittedHash === storedHash;',
        '};',
    ]),
    sp(),

    h3('5.2.4 Schedule Conflict Detection — appliesOnDate()'),
    jpp('The appliesOnDate() function is the core of TASKTIME\'s scheduling intelligence. It determines whether a recurring schedule "appears" on a given target date without creating individual database records for each future occurrence. This function is called for every existing user schedule during conflict checking and by the nightly cron job:'),
    sp(),
    ...codeBlock([
        '// date.utils.js',
        'export const appliesOnDate = (schedule, targetDate) => {',
        '  // 1. Cannot apply before the schedule\'s start date',
        '  if (targetDate < schedule.scheduleDate) return false;',
        '',
        '  // 2. Cannot apply after the repeatUntil end date',
        '  if (schedule.repeatUntil && targetDate > schedule.repeatUntil)',
        '    return false;',
        '',
        '  switch (schedule.recurrence) {',
        '    case "NONE":',
        '      // One-time: only applies on the exact scheduleDate',
        '      return sameUTCDate(targetDate, schedule.scheduleDate);',
        '',
        '    case "DAILY":',
        '      // Applies on every day from scheduleDate onwards',
        '      return true;',
        '',
        '    case "WEEKLY":',
        '      // Applies only on matching days of the week',
        '      return schedule.repeatOnDays.includes(targetDate.getUTCDay());',
        '      // getUTCDay(): 0=Sun, 1=Mon, 2=Tue ... 6=Sat',
        '',
        '    case "MONTHLY":',
        '      // Applies on the same date number each month',
        '      return targetDate.getUTCDate() === schedule.scheduleDate.getUTCDate();',
        '',
        '    default: return false;',
        '  }',
        '};',
    ]),
    sp(),

    h3('5.2.5 Nightly Missed Schedule Detection Cron'),
    jpp('The most critical background job runs every day at 00:05 UTC — after midnight so "yesterday" is well-defined across all timezones. It fetches all active schedules, applies the appliesOnDate() virtual expansion, filters out completed ones, and creates MissedSchedule records in a Prisma transaction:'),
    sp(),
    ...codeBlock([
        '// cron/missedSchedule.cron.js',
        'cron.schedule("5 0 * * *", async () => {',
        '  const yesterday = new Date();',
        '  yesterday.setUTCDate(yesterday.getUTCDate() - 1);',
        '  yesterday.setUTCHours(0, 0, 0, 0);',
        '',
        '  const [allSchedules, completions] = await Promise.all([',
        '    prisma.schedule.findMany({',
        '      where: { OR: [{ repeatUntil: null }, { repeatUntil: { gte: yesterday } }] }',
        '    }),',
        '    prisma.scheduleCompletion.findMany({',
        '      where: { completedOn: yesterday },',
        '      select: { scheduleId: true }',
        '    })',
        '  ]);',
        '',
        '  const completedSet = new Set(completions.map(c => c.scheduleId));',
        '  const missed = allSchedules.filter(s =>',
        '    appliesOnDate(s, yesterday) && !completedSet.has(s.id)',
        '  );',
        '',
        '  if (missed.length > 0) {',
        '    await prisma.missedSchedule.createMany({',
        '      data: missed.map(s => ({',
        '        scheduleId: s.id,',
        '        userId: s.userId,',
        '        missedOn: yesterday',
        '      })),',
        '      skipDuplicates: true  // idempotent — safe to re-run',
        '    });',
        '  }',
        '});',
    ]),
    sp(),

    h3('5.2.6 Streaming AI Response to Browser'),
    jpp('The AI orchestrator streams LangGraph output token-by-token to the browser using Node.js res.write() for SSE. The frontend\'s ReadableStream consumer renders each token as it arrives, creating the real-time typing effect:'),
    sp(),
    ...codeBlock([
        '// Backend: aiOrchestrator.service.js',
        'export const streamAiResponse = async (userId, message, conversationId, res) => {',
        '  res.setHeader("Content-Type", "text/plain; charset=utf-8");',
        '  res.setHeader("Transfer-Encoding", "chunked");',
        '',
        '  const stream = await graph.stream(state, config);',
        '  for await (const chunk of stream) {',
        '    const token = extractToken(chunk);',
        '    if (token) res.write(token);',
        '  }',
        '  res.end();',
        '};',
        '',
        '// Frontend: AI chat component',
        'const response = await fetch("/api/ai/chat/stream", { method: "POST", ... });',
        'const reader   = response.body.getReader();',
        'const decoder  = new TextDecoder();',
        'let fullText   = "";',
        '',
        'while (true) {',
        '  const { done, value } = await reader.read();',
        '  if (done) break;',
        '  const chunk = decoder.decode(value, { stream: true });',
        '  fullText += chunk;',
        '  setStreamingMessage(fullText);  // triggers React re-render per token',
        '}',
    ]),
    sp(),

    h3('5.2.7 Razorpay Webhook HMAC Verification'),
    jpp('Razorpay sends a SHA-256 HMAC signature in the x-razorpay-signature header of every webhook event. TASKTIME verifies this before processing any payment event — preventing fraudulent payment notifications from triggering credit grants:'),
    sp(),
    ...codeBlock([
        '// webhooks/razorpay.webhook.js',
        'export const handleRazorpayWebhook = async (req, res) => {',
        '  const signature = req.headers["x-razorpay-signature"];',
        '  const body      = JSON.stringify(req.body);',
        '  const secret    = process.env.RAZORPAY_WEBHOOK_SECRET;',
        '',
        '  const expectedSig = crypto',
        '    .createHmac("sha256", secret)',
        '    .update(body)',
        '    .digest("hex");',
        '',
        '  if (signature !== expectedSig) {',
        '    return res.status(401).json({ error: "Webhook signature invalid" });',
        '  }',
        '',
        '  const event = req.body.event;',
        '  if (event === "subscription.charged") {',
        '    await billingService.handleSubscriptionCharged(req.body.payload);',
        '  } else if (event === "payment.captured") {',
        '    await billingService.handleTopUpCaptured(req.body.payload);',
        '  }',
        '  res.status(200).json({ received: true });',
        '};',
    ]),
    sp(),

    h3('5.2.8 Axios Token Refresh Interceptor (Frontend)'),
    ...codeBlock([
        '// Frontend: axios interceptor for transparent token refresh',
        'axiosInstance.interceptors.response.use(',
        '  (response) => response,',
        '  async (error) => {',
        '    const originalRequest = error.config;',
        '    if (error.response?.status === 401 && !originalRequest._retry) {',
        '      originalRequest._retry = true;  // prevent infinite loop',
        '      try {',
        '        const { data } = await axios.post("/api/auth/refresh-token", {},',
        '          { withCredentials: true }   // sends HttpOnly refresh cookie',
        '        );',
        '        setAccessToken(data.accessToken);',
        '        originalRequest.headers.Authorization =',
        '          `Bearer ${data.accessToken}`;',
        '        return axiosInstance(originalRequest); // retry original request',
        '      } catch {',
        '        clearAuth();',
        '        window.location.href = "/login";',
        '      }',
        '    }',
        '    return Promise.reject(error);',
        '  }',
        ');',
    ]),
    sp(),

    h2('5.3 Implementation Challenges and Solutions'),
    tbl(
        ['Challenge Encountered', 'Root Cause', 'Solution Implemented'],
        [
            ['AI sets dueDate to today for ALL tasks', 'LLM defaulted to current date when no deadline was specified by user', 'Added explicit Rule #4 to system prompt: "dueDate MUST be null unless user gives an explicit deadline." Added negative examples in few-shot section of the prompt.'],
            ['Sarvam-M outputs prose instead of JSON', 'Chat-only model sometimes ignored JSON format instructions and wrote conversational responses', 'Set temperature=0 for deterministic output. Added regex-based JSON fence stripping. Added JSON.parse() failure fallback to {action:"unknown"} — never throws.'],
            ['"Create those tasks" produces no action in Sarvam-M', 'Without tool calling, "create them all" was interpreted as a text reference, not a command', 'Added Rule #11 to Sarvam intent prompt: "If user says create them/create all referring to previous messages — extract titles from YOUR previous response, output create_tasks_bulk."'],
            ['Gemini content arrives as Array<{type, text}> not string', 'Gemini\'s multipart content format differs from OpenAI\'s plain string format', 'Implemented normalizeContent() in contentUtils.js handling both formats. Applied in all 5 graph nodes, token counter, and reflection error checker.'],
            ['Schedule conflict check misses recurring schedules', 'Initial implementation only fetched NONE recurrence schedules for conflict detection', 'Rewrote conflict check to fetch ALL user schedules regardless of recurrence, then run appliesOnDate() on each before time overlap check.'],
            ['Credit deduction race condition risk under concurrent requests', 'Two concurrent AI requests could both read the same balance and both deduct, resulting in negative balance', 'Implemented Prisma $transaction() with SELECT FOR UPDATE semantics — transaction serialises concurrent credit deductions atomically.'],
        ],
        [2200, 2500, 4660],
    ),
    sp(),

]

module.exports = { content };